### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by ofirkris** [mnmjh1215/diya-CartoonGAN#1]
Hi thanks for sharing your work.
I'd like to compare your results to the original CartonGAN implementation, and I have several questions:

1. What training data should we use? can you share it?
2. Can you share your pre-trained models?
3. Can you add simple instructions on how to test (where to place models, where to place input and output images etc. ?

P.S -  Link to your presentation isn't working

**Comment by mnmjh1215** [comment]
Hi thanks for having interest in my work.

1. For cartoon images, we used frames from Makoto Shinkai's movies for cartoon image data. For photo images, we crawled images from flickr. 
2. If you leave your email address, I can share pre-trained models.
3.  You can modify ```config.py``` to change image paths. As for model path, you can see instructions by running ```python CartoonGAN_main.py --help```. 
Please note that we used ```torchvision.datasets.ImageFolder``` to load images. If your ```photo_image_dir``` in ```config.py``` is ```data/photo/```, then you should place images inside some directory under ```data/photo/ ```

Also, thanks for notifying me that link to the presentation is not working.

**Comment by ofirkris** [comment]
Thanks JiHwan.

Regarding models - I would like to test them, thanks
My email is ofir[@]smedia[.]co[.]il
(remove brackets)

**Comment by innovationcreators** [comment]
Hi @mnmjh1215 ,
I have looked at your work it's good and I want to train this on my own datasets, so if possible can you share your the pre-trained model with me.
My email id - innovationcreators786@gmail.com

Thanks.
